### PR TITLE
Add: keybinding to open terminal at current file's directory

### PR DESCRIPTION
**Pull request by chenlijun99**
### PR Prelude

Thank you for working on SpaceVim! :)

Please complete these steps and check these boxes before filing your PR:

- [x] I have read and understood SpaceVim's [CONTRIBUTING](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md) document.
- [x] I have read and understood SpaceVim's [CODE_OF_CONDUCT](https://github.com/SpaceVim/SpaceVim/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I understand my PR may be closed if it becomes obvious I didn't actually perform all of these steps.

### Why this change is necessary and useful?

[Please explain **in detail** why the changes in this PR are needed.]

See issue #2479

### CODE REVIEW

**Comment by chenlijun99** [comment]
This pull request doesn't yet cover the case where a terminal is not closed but the keybinding is invoked again.

Discussions are welcome.

General ideas on how this can be addressed:

* Don't use lcd approach. Instead, on each "SPC \"", send keys to the terminal with vim's `term_sendkeys()` and neovim's `chansend()`. Something like `cd <path>\<cr>\<c-l>`.
* When switching to terminal, check whether it's working directory is the desired one. If not, close it and proceed with creating a new terminal with the desired working directory.

**Comment by wsdjeg** [comment]
well, I think `SPC '` is used to open project shell, this shell can be hidden, and the history in this shell should not be cleared when hide the shell windows.

the `SPC "` key binding should be able to open new shell if no shell windows exist, the dir of the shell is buffer dir. and if the project shell is openen, `SPC "` should be same as `SPC '` which is just switch to shell windows. because for user who windows is samll, I do not think open two shell windows is a good idea.

send key is not a good idea, bucase, you do not know if the command in current current shell  widnow is exit. for example if you are run `jekylll server start` and this command is not exit, then you can not send `cd path` to that shell.

**Comment by wsdjeg** [comment]
BTW, no need to use `lcd`, just start a shell windows via `term_open()`, this function support specific the cwd.

**Comment by chenlijun99** [comment]
I totally overlooked the `cwd` options. That would simplify a lot of things.

Yeah, I totally agreen that send keys would be a really fragile implementation.

> the `SPC "` key binding should be able to open new shell if no shell windows exist, the dir of the shell is buffer dir. and if the project shell is openen, `SPC "` should be same as `SPC '` which is just switch to shell windows. because for user who windows is samll, I do not think open two shell windows is a good idea.

This would be the simplest, but not the most user-friendly solution.

A harder but more user friendly solution would be to create a terminal for each different directory and to show only the active one.

**Comment by wsdjeg** [comment]
> A harder but more user friendly solution would be to create a terminal for each different directory and to show only the active one.

when press `SPC "`, check if the shell windows exits, if the shell exist, check the shell dir ( which can be set when create a shell windows, use b:var), if the b:var is not same, just hide the shell windows, create a new shell for current buffer dir.

**Comment by chenlijun99** [comment]
Yeah, that's exactly what I was planning to do.
Let's see if I have some time to implement it.

**Comment by chenlijun99** [comment]
The corner case is now handled pretty well.

**Pull request merged**
